### ISSUE TITLE
The beginning and end of sentences of "Pv" pop up message are hidden

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#48] opened 2017-07-17 09:20 UTC
On the “Pv” pop up message, the beginning of sentence and the end of row the letters are hidden. Please fix this point as appropriate.

![issue_3](https://user-images.githubusercontent.com/29400470/28261974-8db1320c-6b0b-11e7-8041-0e9c08116130.JPG)

**Comment by ifoche** [comment] 2017-07-17 13:22
Duplicate of #49

**Closed as completed by ifoche** 2017-07-17 13:23 UTC
Labels: duplicate
